# Generated by Django 3.2.6 on 2021-08-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='treatment_type',
            field=models.CharField(choices=[('DRY', 'Dryness'), ('OIL', 'Oily'), ('ACNE', 'Acne'), ('AGE', 'Aging'), ('ROSE', 'Rosacea'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
